likedMovies/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("movie.urls", namespace='movie')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path
from .import views
app_name = 'movie'
urlpatterns = [
    path("", views.HomeView.as_view(), name='home'),
    path("create/", views.CreateMovieView.as_view(), name="create"),
    path("test/", views.TestTemplateView.as_view(), name='test'),
    path("detail/<int:pk>", views.MovieDetailView.as_view(), name='detail'),
    path("delete/<int:pk>", views.MovieDeleteView.as_view(), name='delete'),
    path("update/<int:pk>", views.MovieUpdateView.as_view(), name='update'),

    # path("add/", views.AddCategoryView.as_view(), name='add')
]

movie/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)

    def __str__(self):
        return f"{self.name}"

class Movie(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100)
    poster = models.ImageField("Poster", upload_to='posters/')
    year = models.CharField(max_length=5)
    rating = models.FloatField(default=1.0)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name_plural = "Movies"
        ordering = ["-id"]
        
class Movie_Shots(models.Model):
    title = models.CharField('Nomi', max_length=150, blank=True, null=True)
    desc = models.TextField("Kadr haqida", blank=True, null=True)
    image = models.ImageField('Kadr', upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name='Film',
                    on_delete=models.CASCADE,
                    null=True, blank=True)


    def __str__(self):
        return self.title


    class Meta:
        verbose_name = 'Kadr'
        verbose_name_plural = 'Kadrlar'

movie/views.py
from django.shortcuts import render
from django.views.generic.base import View , TemplateView
from django.views.generic import ListView, DetailView,DeleteView
from django.views.generic.edit import CreateView, FormView, UpdateView
from django.urls import reverse
from .models import Movie, Category
# Create your views here.

class HomeView(ListView):
    template_name = "index.html"
    model = Movie
    context_object_name = "movies"

class CreateMovieView(CreateView):
    template_name = "create.html"
    model = Movie
    fields =  ["title", "year" ,"poster","rating"]
    success_url = '/'
    # exclude = ["slug"]

class MovieDeleteView(DeleteView):
    model = Movie
    success_url = '/'

class MovieUpdateView(UpdateView):
    template_name = 'create.html'
    model = Movie
    fields = ["title", "year", "rating", "poster"]
    success_url = '/'

class TestTemplateView(TemplateView):
    template_name = 'test.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["movies"] = Movie.objects.all()
        return context

class MovieDetailView(DetailView):
    model = Movie
    template_name = 'detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        return context


# class AddCategoryView(FormView):
#     template_name = 'create.html'
#     form_class = Category
#     # initial = {'name':"Write your category name"}
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["categories"] = Category.objects.all()
#         return context
#
#     def form_valid(self, form):
#         form.save()
#         return super().form_valid(form)
#
#     def get_form(self, form_class=None):
#         self.object = super().get_form(form_class)
#         return self.object
#
#     def get_success_url(self):
#         return reverse("movie:detail",self.object.cleaned_data["pk"].pk )

templates/create.html
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.1/css/bootstrap.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.1/js/bootstrap.min.js"></script>
    <title>My Movies</title>
</head>
<body style="background: #212121;">
<style>
    *{
        color: aliceblue;
    }
</style>
<div class="navbar bg-warning">
    <div class="navbar-brand">
        <a href="#" class="logo">My Movies</a>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="text-center mt-5">
            <h2 class="text-light">All my movies</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="p-3">
                <form action="" method="post" enctype="multipart/form-data">
                    {{ form|crispy }}
                    {% csrf_token %}
                    <input type="submit" value="Create" class="btn btn-block bg-danger">
                </form>
            </div>
        </div>
    </div>
</div>

</body>
</html>

templates/detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.1/css/bootstrap.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.1/js/bootstrap.min.js"></script>
    <title>My Movies</title>
</head>
<body style="background: #212121;">
<style>
    *{
        color: aliceblue;
    }
</style>
<div class="navbar bg-warning">
    <div class="navbar-brand">
        <a href="#" class="logo">My Movies</a>
    </div>
    <div class="d-flex">
        <a href="{% url 'movie:create' %}" class="btn btn-danger ">ADD</a>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="text-center mt-5">
            <h2 class="text-light">All my movies</h2>
        </div>
    </div>
    <div class="row">

        <div class="col-sm-12 col-md-4">
            <br><a href=""><img src="{{movie.poster.url}}" alt=""></a>
        </div>
        <div class="col-sm-12 col-md-8">
            <div class="movie">

                <h3 class="mt-2">{{ movie.title}}</h3>
                <br>
                <p>{{ movie.text     }}</p>
                <div class="row">
                    <div class="col-sm-6">
                        <ul>
                        <li><h4>Categories</h4></li>
                            {% for category in categories %}
                            <li><h5>{{ category.name }}</h5></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col-sm-6">
                        <a href="#"><span>{{ movie.year }}</span></a>
                        <a href="#"><i class="fas fa-heart"></i></a>
                        <a href="#"><i class="fas fa-eye"></i></a>
                        <a href="#"><i class="fas fa-star"></i></a>
                        <span>{{ movie.rating }}</span>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

</body>
</html>

templates/index.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.1/css/bootstrap.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.1/js/bootstrap.min.js"></script>
    <title>My Movies</title>
</head>

<body style="background: #212121;">
    <style>
        * {
            color: aliceblue;
        }
    </style>
    <div class="navbar bg-warning">
        <div class="navbar-brand">
            <a href="#" class="logo">My Movies</a>
        </div>
        <div class="d-flex">
            <a href="{% url 'movie:create' %}" class="btn btn-danger ">ADD</a>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="text-center mt-5">
                <h2 class="text-light">All my movies</h2>
            </div>
        </div>
        <div class="row">
            {% for movie in movies %}
            <div class="col-sm-6 col-md-3">
                <br>
                <div class="movie">
                    <a href="{% url 'movie:detail' movie.id %}">
                        <img src="{{movie.poster.url}}" alt="">
                    </a>
                    <h3 class="mt-2">{{ movie.title}}</h3>
                    <div class="row">
                        <div class="col-sm-6">
                            <a href="#"><span>{{ movie.year }}</span></a>
                            <h3>
                                <a href="{% url 'movie:delete' movie.id %}"> <i class="fas fa-trash"></i></a>
                                <a href="{% url 'movie:update' movie.id %}"> <i class="fas fa-sync"></i></a>
                            </h3>
                        </div>
                        <div class="col-sm-6">
                            <a href="#"><i class="fas fa-heart"></i></a>
                            <a href="#"><i class="fas fa-eye"></i></a>
                            <a href="#"><i class="fas fa-star"></i></a>
                            <span>{{ movie.rating }}</span>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</body>

</html>

templates/movie/movie_confirm_delete.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<center>
    <form action="" method="post">
        <h3>Are your sure ?</h3>
        {% csrf_token %}
        <input type="submit">
    </form>
</center>
</body>
</html>

templates/test.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<ul>
    {% for movie in movies %}
    <li>{{ movie.title }}</li>
    {% endfor %}

</ul>

</body>
</html>